### ISSUE TITLE
Mail icon not properly exportable

### ISSUE THREAD

**Issue by dumazy** [dumazy/begum-goktas-portfolio#1]
The [mail icon](https://www.figma.com/file/O4hUyINANMcSUKeEKdTg3E/BG?node-id=415%3A547&t=p52KTmq2XcmcTpRF-4) is made of multiple vectors and is wrongly grouped, not allowing it to be exported as a single SVG file.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/2174500/214698009-40a620fa-b3db-4601-a342-22bb4c89340c.png">

Create an extra group for only the two vectors, so that new group can be exported as a single SVG.
Maybe add some clarity in the names. Suggestion:

```
Mail item (instead of Group 4)
 |-- Mail icon (the new group)
 |     |-- Vector
 |     |-- Vector
 |-- Touch area (instead of Ellipse 3)
 ```

**Comment by begumgoktas** [comment]
I fixed it baby. thank u so much. I love u so much. kissy kissy

**Comment by dumazy** [comment]
Thanks honey :) 
I was able to export the icon now. It's added in the project and will be available on the test version in a few minutes.

Closing this issue.

**Comment by begumgoktas** [comment]
> The [mail icon](https://www.figma.com/file/O4hUyINANMcSUKeEKdTg3E/BG?node-id=415%3A547&t=p52KTmq2XcmcTpRF-4) is made of multiple vectors and is wrongly grouped, not allowing it to be exported as a single SVG file.
> 
> <img alt="image" width="234" src="https://user-images.githubusercontent.com/2174500/214698009-40a620fa-b3db-4601-a342-22bb4c89340c.png">
> 
> Create an extra group for only the two vectors, so that new group can be exported as a single SVG. Maybe add some clarity in the names. Suggestion:
> 
> ```
> Mail item (instead of Group 4)
>  |-- Mail icon (the new group)
>  |     |-- Vector
>  |     |-- Vector
>  |-- Touch area (instead of Ellipse 3)
> ```

I did it baby! Thanks! :)
